const f = (key, label, type = "text", required = false, options) => ({
  key,
  label,
  type,
  required,
  options,
});
export const styles = [
  "严肃历史小说",
  "编年史风格",
  "档案纪实风",
  "维多利亚时代报纸风",
  "史诗战争风",
  "蒸汽朋克风",
  "人物视角叙事",
  "网文爽文风",
];
export const schemas = {
  worldline: {
    title: "世界线",
    id: "worldlineId",
    name: "worldlineName",
    fields: [
      f("worldlineName", "世界线名称", "text", true),
      f("gameName", "游戏名称", "text", true),
      f("mainCountry", "主控国家"),
      f("startYear", "起始年份", "number"),
      f("currentYear", "当前年份", "number"),
      f("narrativeStyle", "叙事风格", "select", false, styles),
      f("description", "世界线简介", "textarea"),
    ],
  },
  event: {
    title: "时间线事件",
    id: "eventId",
    name: "eventTitle",
    fields: [
      f("eventTitle", "事件标题", "text", true),
      f("eventYear", "年份", "number", true),
      f("eventDate", "事件日期"),
      f("country", "国家"),
      f("eventType", "事件类型", "select", true, [
        ["war", "战争"],
        ["diplomacy", "外交"],
        ["law", "法律改革"],
        ["economy", "经济"],
        ["revolution", "革命"],
        ["technology", "科技"],
        ["colony", "殖民"],
        ["government", "政权"],
        ["character", "人物"],
        ["divergence", "历史分歧"],
        ["other", "其他"],
      ]),
      f("importanceLevel", "重要程度", "select", false, [
        ["1", "背景变化"],
        ["2", "重要事件"],
        ["3", "转折点"],
        ["4", "世界线分歧"],
      ]),
      f("relatedForces", "相关势力"),
      f("stageId", "所属阶段编号", "number"),
      f("summary", "事件摘要", "textarea"),
      f("aiDescription", "小说片段", "textarea"),
      f("impactAnalysis", "影响分析", "textarea"),
      f("novelPotential", "适合生成小说", "select", false, [
        ["0", "否"],
        ["1", "是"],
      ]),
    ],
  },
  stage: {
    title: "历史阶段",
    id: "stageId",
    name: "stageName",
    fields: [
      f("stageName", "阶段名称", "text", true),
      f("stageTheme", "阶段主题"),
      f("startYear", "起始年份", "number"),
      f("endYear", "结束年份", "number"),
      f("stageSummary", "阶段摘要", "textarea"),
    ],
  },
  chapter: {
    title: "小说章节",
    id: "chapterId",
    name: "chapterTitle",
    fields: [
      f("chapterTitle", "章节标题", "text", true),
      f("chapterOrder", "章节顺序", "number"),
      f("stageId", "所属阶段编号", "number"),
      f("writingStyle", "叙事风格", "select", false, styles),
      f("relatedEventIds", "相关事件编号（逗号分隔）"),
      f("content", "章节正文", "textarea"),
    ],
  },
  nation: {
    title: "国家档案",
    id: "stateId",
    name: "countryName",
    fields: [
      f("countryName", "国家名称", "text", true),
      f("recordYear", "记录年份", "number", true),
      f("government", "政体"),
      f("economyStatus", "经济状况"),
      f("militaryStatus", "军事状况"),
      f("diplomacyStatus", "外交状况"),
      f("socialConflict", "社会矛盾", "textarea"),
      f("aiSummary", "综合摘要", "textarea"),
    ],
  },
  character: {
    title: "人物档案",
    id: "characterId",
    name: "characterName",
    fields: [
      f("characterName", "人物姓名", "text", true),
      f("country", "国家"),
      f("faction", "派系"),
      f("identityName", "身份"),
      f("characterType", "人物类型"),
      f("personality", "性格"),
      f("portraitUrl", "肖像地址（站内路径或 HTTPS）"),
      f("biography", "人物传记", "textarea"),
    ],
  },
  illustration: {
    title: "插图",
    id: "illustrationId",
    name: "illustrationTitle",
    fields: [
      f("illustrationTitle", "插图标题"),
      f("chapterId", "章节编号", "number"),
      f("eventId", "事件编号", "number"),
      f("stageId", "阶段编号", "number"),
      f("characterId", "人物编号", "number"),
      f("illustrationType", "插图类型"),
      f("styleType", "画面风格"),
      f("prompt", "绘图提示词", "textarea"),
      f("negativePrompt", "排除内容", "textarea"),
      f("imageUrl", "图片地址（站内路径或 HTTPS）"),
    ],
  },
  screenshot: {
    title: "截图记录",
    id: "screenshotId",
    name: "originalName",
    fields: [],
  },
  aiTask: { title: "AI 任务", id: "taskId", name: "taskType", fields: [] },
};
